# Generated by Django 2.1.2 on 2018-11-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_squashed_0003_auto_20181031_0721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
